services:

  # MySQL database service
  mysql:
    image: mysql:9.0.0
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Spring Boot application
  springboot-app:
    build:
      context: ./springboot-app # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Specify the Dockerfile name if not default
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME_FILE: ${SPRING_DATASOURCE_USERNAME_FILE}
      SPRING_DATASOURCE_PASSWORD_FILE: ${SPRING_DATASOURCE_PASSWORD_FILE}
